# AI Editor - Generates and applies content modifications via LLM
# Rate limited, token limited, validates all patches

import json
import re
import asyncio
from datetime import datetime, timezone
from typing import Dict, List, Any, Optional, Tuple
from pydantic import BaseModel, Field
import logging

from emergentintegrations.llm.chat import LlmChat
from emergentintegrations.llm.chat import UserMessage

from site_content import (
    SiteContent, ChangeLogEntry, 
    validate_content, validate_patch_allowed,
    ALLOWED_EDIT_PATHS
)

logger = logging.getLogger(__name__)

# ============================================
# RATE LIMITING & TOKEN LIMITS
# ============================================

# Token limits per request (input + output)
MAX_INPUT_TOKENS = 2000
MAX_OUTPUT_TOKENS = 2000
MAX_REQUEST_LENGTH = 500  # Max characters in user request

# Rate limiting (per site per hour)
RATE_LIMIT_PER_HOUR = 20
rate_limit_cache: Dict[str, List[datetime]] = {}

def check_rate_limit(site_id: str) -> Tuple[bool, str]:
    """Check if rate limit exceeded for site"""
    now = datetime.now(timezone.utc)
    hour_ago = now.replace(microsecond=0, second=0, minute=now.minute)
    
    if site_id not in rate_limit_cache:
        rate_limit_cache[site_id] = []
    
    # Clean old entries
    rate_limit_cache[site_id] = [
        t for t in rate_limit_cache[site_id] 
        if (now - t).total_seconds() < 3600
    ]
    
    if len(rate_limit_cache[site_id]) >= RATE_LIMIT_PER_HOUR:
        return False, f"Rate limit superato: max {RATE_LIMIT_PER_HOUR} richieste/ora. Riprova tra qualche minuto."
    
    return True, ""

def record_request(site_id: str):
    """Record a request for rate limiting"""
    if site_id not in rate_limit_cache:
        rate_limit_cache[site_id] = []
    rate_limit_cache[site_id].append(datetime.now(timezone.utc))

# ============================================
# PRESET PROMPTS
# ============================================

PRESET_PROMPTS = {
    "update_hours": {
        "name": "Aggiorna Orari",
        "icon": "clock",
        "prompt_template": """Aggiorna gli orari di apertura con i seguenti cambiamenti: {user_input}

Regole:
- Mantieni coerenza EN + lingua locale ({locale_lang})
- Formato orario: HH:MM (24h)
- Se un giorno è chiuso, imposta closed=true
- Puoi aggiungere note brevi (es. "cucina aperta fino alle 22")
- Traduci le note in entrambe le lingue"""
    },
    
    "update_menu": {
        "name": "Aggiorna Menu/Servizi", 
        "icon": "utensils",
        "prompt_template": """Aggiorna la sezione menu/servizi con questi cambiamenti: {user_input}

Regole:
- Mantieni struttura: categories → items
- Ogni item deve avere name_local e name_en
- Se manca una traduzione, generala
- Prezzi opzionali (formato: "€XX.XX" o "da €XX")
- mode deve essere "menu" per ristoranti, "services" per altri"""
    },
    
    "rewrite_texts": {
        "name": "Riscrivi Testi",
        "icon": "pen",
        "prompt_template": """Riscrivi 'Chi siamo' e la tagline hero: {user_input}

Regole:
- Tono professionale e concreto
- Massimo 80-120 parole per 'Chi siamo'
- Tagline breve e d'impatto (max 10 parole)
- Genera sia versione locale ({locale_lang}) che EN
- Adatta il tono alla categoria: {category}"""
    },
    
    "update_contacts": {
        "name": "Aggiorna Contatti",
        "icon": "phone",
        "prompt_template": """Aggiorna i contatti con: {user_input}

Regole:
- Verifica formato telefono/whatsapp (solo numeri, +, spazi)
- Verifica formato email (deve contenere @)
- WhatsApp deve essere il contatto principale per CTA
- Non modificare indirizzo, città, paese (sono fissi)"""
    },
    
    "manage_gallery": {
        "name": "Gestisci Galleria",
        "icon": "images",
        "prompt_template": """Aggiorna la galleria: {user_input}

Regole:
- Solo URL esterni validi (https://)
- Puoi aggiungere, rimuovere, riordinare immagini
- Caption opzionali in locale + EN
- L'ordine è determinato dal campo 'order' (0 = prima)"""
    },
    
    "update_seo": {
        "name": "SEO Base",
        "icon": "search",
        "prompt_template": """Genera/aggiorna SEO per il sito: {user_input}

Regole:
- Title: max 60 caratteri, include nome attività + città + categoria
- Meta description: max 155 caratteri, descrizione accattivante
- Genera versione locale ({locale_lang}) e EN
- Nome attività: {business_name}
- Città: {city}
- Categoria: {category}"""
    }
}

# ============================================
# AI PROPOSAL GENERATION
# ============================================

class AIProposal(BaseModel):
    """Proposal generated by AI Editor"""
    success: bool
    request: str
    changes_summary: List[str] = Field(default_factory=list)
    patch: Dict[str, Any] = Field(default_factory=dict)
    validation_errors: List[str] = Field(default_factory=list)
    preview_content: Optional[Dict[str, Any]] = None
    error: Optional[str] = None

def get_system_prompt(content: SiteContent) -> str:
    """Generate system prompt for AI Editor"""
    return f"""Sei un assistente per la modifica di contenuti di siti web aziendali.

REGOLE FONDAMENTALI:
1. Puoi modificare SOLO questi campi:
   - business: name, category, address, phone, whatsapp, email
   - opening_hours: orari per ogni giorno (mon-sun)
   - menu_or_services: categorie e items
   - gallery: immagini (solo URL esterni)
   - about_text: testo chi siamo (local + en)
   - hero: tagline (local + en)
   - seo: title e meta (local + en)

2. NON puoi modificare:
   - Layout, design, colori, componenti
   - Codice, routing, script
   - Paese, città, URL Google Maps
   - ID e metadati interni

3. MULTILINGUA OBBLIGATORIO:
   - Lingua locale: {content.locale_lang}
   - Ogni testo deve avere versione locale + inglese
   - Mai mix di lingue nella stessa stringa

4. FORMATO OUTPUT:
   Rispondi SEMPRE in questo formato JSON:
   {{
     "changes_summary": ["Modifica 1 in italiano", "Modifica 2 in italiano"],
     "patch": {{
       "campo.sottocampo": "nuovo valore",
       ...
     }}
   }}

DATI ATTUALI DEL SITO:
- Nome: {content.business.name}
- Categoria: {content.business.category}  
- Città: {content.business.city}
- Lingua locale: {content.locale_lang}
"""

async def generate_ai_proposal(
    content: SiteContent,
    user_request: str,
    preset_type: Optional[str] = None,
    emergent_key: str = ""
) -> AIProposal:
    """
    Generate a modification proposal using AI.
    Returns structured patch + human-readable summary.
    """
    
    # Validate request length
    if len(user_request) > MAX_REQUEST_LENGTH:
        return AIProposal(
            success=False,
            request=user_request[:100] + "...",
            error=f"Richiesta troppo lunga: max {MAX_REQUEST_LENGTH} caratteri"
        )
    
    # Check rate limit
    allowed, error_msg = check_rate_limit(content.demo_id)
    if not allowed:
        return AIProposal(
            success=False,
            request=user_request,
            error=error_msg
        )
    
    # Build prompt
    if preset_type and preset_type in PRESET_PROMPTS:
        preset = PRESET_PROMPTS[preset_type]
        prompt = preset["prompt_template"].format(
            user_input=user_request,
            locale_lang=content.locale_lang,
            category=content.business.category,
            business_name=content.business.name,
            city=content.business.city
        )
    else:
        prompt = f"""Richiesta dell'utente: {user_request}

Analizza la richiesta e genera le modifiche appropriate.
Se la richiesta riguarda testi, genera sempre versione locale ({content.locale_lang}) e inglese."""
    
    # Current content summary for context
    current_summary = f"""
Contenuto attuale:
- Orari: {[f"{d}: {'Chiuso' if getattr(content.opening_hours, d).closed else f'{getattr(content.opening_hours, d).open}-{getattr(content.opening_hours, d).close}'}" for d in ['mon','tue','wed','thu','fri','sat','sun']]}
- Menu/Servizi: {len(content.menu_or_services.categories)} categorie
- Galleria: {len(content.gallery)} immagini
- Chi siamo: {content.about_text.local[:100] if content.about_text.local else 'Non impostato'}...
- Contatti: tel={content.business.phone}, wa={content.business.whatsapp}, email={content.business.email}
"""
    
    full_prompt = prompt + "\n" + current_summary
    
    try:
        chat = LlmChat(
            api_key=emergent_key,
            session_id=f"ai_editor_{content.demo_id}_{datetime.now().timestamp()}",
            system_message=get_system_prompt(content)
        ).with_model("openai", "gpt-5.2")
        
        message = UserMessage(text=full_prompt)
        response = await chat.send_message(message)
        
        # Record request for rate limiting
        record_request(content.demo_id)
        
        # Parse response
        clean_response = response.strip()
        if clean_response.startswith("```"):
            clean_response = re.sub(r'^```(?:json)?\s*', '', clean_response)
            clean_response = re.sub(r'\s*```$', '', clean_response)
        
        try:
            result = json.loads(clean_response)
        except json.JSONDecodeError as e:
            logger.error(f"AI response parse error: {e}\nResponse: {clean_response[:500]}")
            return AIProposal(
                success=False,
                request=user_request,
                error="Errore nel parsing della risposta AI. Riprova con una richiesta più specifica."
            )
        
        changes_summary = result.get("changes_summary", [])
        patch = result.get("patch", {})
        
        # Validate patch
        validation_errors = validate_patch_allowed(patch)
        
        # Check for suspicious content
        patch_str = json.dumps(patch).lower()
        suspicious_patterns = [
            r'<script', r'javascript:', r'onclick', r'onerror',
            r'data:text/html', r'document\.', r'window\.'
        ]
        for pattern in suspicious_patterns:
            if re.search(pattern, patch_str, re.I):
                validation_errors.append(f"Contenuto sospetto rilevato: {pattern}")
        
        return AIProposal(
            success=len(validation_errors) == 0,
            request=user_request,
            changes_summary=changes_summary,
            patch=patch,
            validation_errors=validation_errors
        )
        
    except Exception as e:
        logger.error(f"AI proposal generation error: {str(e)}")
        return AIProposal(
            success=False,
            request=user_request,
            error=f"Errore generazione proposta: {str(e)}"
        )

# ============================================
# APPLY PATCH TO CONTENT
# ============================================

def apply_patch_to_content(content: SiteContent, patch: Dict[str, Any]) -> Tuple[SiteContent, List[str]]:
    """
    Apply a patch to SiteContent.
    Returns (updated_content, errors).
    """
    errors = []
    
    # First validate patch
    patch_errors = validate_patch_allowed(patch)
    if patch_errors:
        return content, patch_errors
    
    # Convert to dict for easier manipulation
    content_dict = content.model_dump()
    
    def set_nested(d: dict, path: str, value: Any):
        """Set a nested value using dot notation"""
        keys = path.split('.')
        for key in keys[:-1]:
            if key.isdigit():
                key = int(key)
            if isinstance(d, list):
                d = d[key]
            else:
                d = d.setdefault(key, {})
        final_key = keys[-1]
        if final_key.isdigit():
            final_key = int(final_key)
        if isinstance(d, list):
            if final_key >= len(d):
                d.append(value)
            else:
                d[final_key] = value
        else:
            d[final_key] = value
    
    # Apply each patch entry
    for path, value in patch.items():
        try:
            # Handle special cases
            if path == "opening_hours" and isinstance(value, dict):
                # Merge hours instead of replace
                for day, hours in value.items():
                    if day in ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']:
                        content_dict['opening_hours'][day].update(hours)
            elif path == "menu_or_services" and isinstance(value, dict):
                # Handle menu/services specially
                if 'mode' in value:
                    content_dict['menu_or_services']['mode'] = value['mode']
                if 'categories' in value:
                    content_dict['menu_or_services']['categories'] = value['categories']
            elif path == "gallery" and isinstance(value, list):
                # Replace gallery
                content_dict['gallery'] = value
            elif path.startswith("gallery.") and path[8:].isdigit():
                # Update single gallery item
                idx = int(path[8:])
                if idx < len(content_dict['gallery']):
                    content_dict['gallery'][idx].update(value)
            else:
                set_nested(content_dict, path, value)
        except Exception as e:
            errors.append(f"Errore applicazione patch '{path}': {str(e)}")
    
    if errors:
        return content, errors
    
    # Update metadata
    content_dict['last_updated'] = datetime.now(timezone.utc).isoformat()
    
    try:
        updated_content = SiteContent.model_validate(content_dict)
        
        # Validate final content
        content_errors = validate_content(updated_content)
        if content_errors:
            return content, content_errors
        
        return updated_content, []
    except Exception as e:
        return content, [f"Errore validazione contenuto: {str(e)}"]

def create_change_log_entry(request: str, changes_summary: List[str], patch: Dict[str, Any]) -> ChangeLogEntry:
    """Create a changelog entry for the modification"""
    return ChangeLogEntry(
        timestamp=datetime.now(timezone.utc),
        request=request,
        changes_summary=changes_summary,
        patch=patch,
        applied_by="ai_editor"
    )

# ============================================
# PREVIEW GENERATION
# ============================================

def generate_preview_diff(original: SiteContent, modified: SiteContent) -> List[Dict[str, Any]]:
    """
    Generate a human-readable diff between original and modified content.
    """
    diffs = []
    
    # Compare business info
    if original.business.model_dump() != modified.business.model_dump():
        for field in ['name', 'phone', 'whatsapp', 'email', 'address']:
            orig_val = getattr(original.business, field)
            mod_val = getattr(modified.business, field)
            if orig_val != mod_val:
                diffs.append({
                    "section": "Contatti",
                    "field": field,
                    "old": orig_val,
                    "new": mod_val
                })
    
    # Compare opening hours
    for day in ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']:
        orig_hours = getattr(original.opening_hours, day)
        mod_hours = getattr(modified.opening_hours, day)
        if orig_hours.model_dump() != mod_hours.model_dump():
            day_names = {'mon': 'Lunedì', 'tue': 'Martedì', 'wed': 'Mercoledì', 
                        'thu': 'Giovedì', 'fri': 'Venerdì', 'sat': 'Sabato', 'sun': 'Domenica'}
            diffs.append({
                "section": "Orari",
                "field": day_names[day],
                "old": f"{'Chiuso' if orig_hours.closed else f'{orig_hours.open}-{orig_hours.close}'}",
                "new": f"{'Chiuso' if mod_hours.closed else f'{mod_hours.open}-{mod_hours.close}'}"
            })
    
    # Compare about text
    if original.about_text.local != modified.about_text.local:
        diffs.append({
            "section": "Chi siamo",
            "field": "Testo locale",
            "old": original.about_text.local[:100] + "..." if len(original.about_text.local) > 100 else original.about_text.local,
            "new": modified.about_text.local[:100] + "..." if len(modified.about_text.local) > 100 else modified.about_text.local
        })
    if original.about_text.en != modified.about_text.en:
        diffs.append({
            "section": "Chi siamo",
            "field": "Testo EN",
            "old": original.about_text.en[:100] + "..." if len(original.about_text.en) > 100 else original.about_text.en,
            "new": modified.about_text.en[:100] + "..." if len(modified.about_text.en) > 100 else modified.about_text.en
        })
    
    # Compare hero
    if original.hero.tagline_local != modified.hero.tagline_local:
        diffs.append({
            "section": "Hero",
            "field": "Tagline locale",
            "old": original.hero.tagline_local,
            "new": modified.hero.tagline_local
        })
    
    # Compare menu/services count
    orig_items = sum(len(c.items) for c in original.menu_or_services.categories)
    mod_items = sum(len(c.items) for c in modified.menu_or_services.categories)
    if orig_items != mod_items:
        diffs.append({
            "section": "Menu/Servizi",
            "field": "Totale items",
            "old": str(orig_items),
            "new": str(mod_items)
        })
    
    # Compare gallery
    if len(original.gallery) != len(modified.gallery):
        diffs.append({
            "section": "Galleria",
            "field": "Numero immagini",
            "old": str(len(original.gallery)),
            "new": str(len(modified.gallery))
        })
    
    # Compare SEO
    if original.seo and modified.seo:
        if original.seo.title_local != modified.seo.title_local:
            diffs.append({
                "section": "SEO",
                "field": "Title locale",
                "old": original.seo.title_local,
                "new": modified.seo.title_local
            })
    elif not original.seo and modified.seo:
        diffs.append({
            "section": "SEO",
            "field": "SEO",
            "old": "Non configurato",
            "new": "Configurato"
        })
    
    return diffs
